name: Dev-Deploy

on:
  push:
    branches: [cloudfront]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-s3:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      deployments: write

    env:
      AWS_REGION: us-east-1
      DEPLOY_BUCKET: cdn-dev-cdndevd19d6ae1-dpcafrrhknm3
      CLOUDFRONT_ID: E46B0FCMVKZ8A

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::545217748721:role/cdn-gh-s3-dev-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload CDN assets to S3
        run: |
          aws s3 sync images/ "s3://$DEPLOY_BUCKET/images/" --delete

      - name: Bust CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          environment: dev
          initial-status: success
