name: Prod-Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-s3:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      deployments: write

    env:
      AWS_REGION: us-east-1
      DEPLOY_BUCKET: fasten-connect-cdn-prod-fastenconnectcdnprod3e2a72-dal92whpt4os
      CLOUDFRONT_ID: E3ZG0G4KWL8QY

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::410145376638:role/fasten-connect-cdn-gh-s3-prod-deploy-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload CDN assets to S3
        run: |
          aws s3 sync connect/ "s3://$DEPLOY_BUCKET/connect/" --delete
          aws s3 sync images/ "s3://$DEPLOY_BUCKET/images/" --delete
          aws s3 sync jwks/ "s3://$DEPLOY_BUCKET/jwks/" --delete
          # do not sync the logos directory, this will be synced directly from the fasten-sources-gen repo

          # Upload root index.html
          aws s3 cp index.html "s3://$DEPLOY_BUCKET/index.html"

      - name: Bust CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/connect/*" "/jwks/*" "/images/*"

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          environment: prod
          environment-url: https://cdn.fastenhealth.com
          initial-status: success
